### ISSUE TITLE
Edge case: Single item in the CComponentInfo section causes the script to crash.

### ISSUE THREAD

**Issue by richardjpike** [Stuyk/gtav-clothing-xml-maximums-script#1]
Thinking that this script can be used to capture custom clothing as well as DLC data.

To replicate:   Using Durty Clothing tool I genreated a clothing package containing one item.  Extracting the xml and throwing it into the mix generated this error.   Multiple <items> work as expected.

Error message:
file:///E:/git_repo/gtav-clothing-xml-maximums-script/index.js:71
        for (let item of data.CPedVariationInfo.compInfos.Item) {
                                                          ^

TypeError: data.CPedVariationInfo.compInfos.Item is not iterable
    at test (file:///E:/git_repo/gtav-clothing-xml-maximums-script/index.js:71:59)
    at file:///E:/git_repo/gtav-clothing-xml-maximums-script/index.js:123:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

**Comment by Stuyk** [comment]
Paste the XML here for reference / testing.

**Comment by Stuyk** [comment]
Open another issue if the above fix doesn't work.
